# Generated by Django 4.2.6 on 2023-10-30 22:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0003_alter_todoitem_due_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todolist",
            old_name="created_oon",
            new_name="created_on",
        ),
    ]
